import { supabaseAdmin } from '@/lib/supabaseServer';

export interface PollRecord {
  id: string;
  question: string;
  category: string;
  yesVotes: number;
  noVotes: number;
  active: boolean;
  autoGenerated: boolean;
  derivedFrom: string;
  lastReset: string;
  lastUpdated: string;
}

export interface PollStateWithMetrics extends PollRecord {
  totalVotes: number;
  yesPercent: number;
  noPercent: number;
}

const DEFAULT_POLL: PollRecord = {
  id: 'poll-coimbatore-metro-1',
  question: 'Will Coimbatore Metro Rail Phase-1 significantly ease Avinashi Road traffic congestion?',
  category: 'INFRASTRUCTURE & CIVIC',
  yesVotes: 0,
  noVotes: 0,
  active: true,
  autoGenerated: true,
  derivedFrom: 'Metro Rail DPR Ministry Approval',
  lastReset: new Date().toISOString(),
  lastUpdated: new Date().toISOString(),
};

let currentPoll: PollRecord = { ...DEFAULT_POLL };
let lastDbFetchTime = 0;
const DB_CACHE_TTL_MS = 3000; // 3 seconds cache to minimize DB roundtrips

function computeMetrics(poll: PollRecord): PollStateWithMetrics {
  const total = (poll.yesVotes || 0) + (poll.noVotes || 0);
  const yesPercent = total > 0 ? Math.round(((poll.yesVotes || 0) / total) * 100) : 0;
  const noPercent = total > 0 ? 100 - yesPercent : 0;

  return {
    ...poll,
    totalVotes: total,
    yesPercent,
    noPercent,
  };
}

/**
 * Load poll configuration from Supabase '__SYSTEM_CONFIG_POLL'
 */
async function syncFromSupabase(): Promise<PollRecord> {
  const now = Date.now();
  if (now - lastDbFetchTime < DB_CACHE_TTL_MS) {
    return currentPoll;
  }

  try {
    const { data, error } = await supabaseAdmin
      .from('enquiries')
      .select('message')
      .eq('user_name', '__SYSTEM_CONFIG_POLL')
      .order('created_at', { ascending: false })
      .limit(1);

    if (!error && data && data.length > 0 && data[0].message) {
      const parsed = JSON.parse(data[0].message);
      if (parsed && typeof parsed.question === 'string') {
        currentPoll = {
          ...DEFAULT_POLL,
          ...parsed,
          yesVotes: typeof parsed.yesVotes === 'number' ? parsed.yesVotes : 0,
          noVotes: typeof parsed.noVotes === 'number' ? parsed.noVotes : 0,
        };
        lastDbFetchTime = now;
        return currentPoll;
      }
    } else {
      // If not yet present in DB, initialize it with 0 votes
      await syncToSupabase(DEFAULT_POLL);
    }
  } catch (err) {
    console.warn('[pollStore] Notice syncing from Supabase:', err);
  }

  lastDbFetchTime = now;
  return currentPoll;
}

/**
 * Save poll state to Supabase '__SYSTEM_CONFIG_POLL'
 */
async function syncToSupabase(poll: PollRecord): Promise<void> {
  try {
    const serialized = JSON.stringify(poll);
    const configUserName = '__SYSTEM_CONFIG_POLL';

    // Delete older config rows to prevent bloat
    await supabaseAdmin
      .from('enquiries')
      .delete()
      .eq('user_name', configUserName);

    // Insert latest snapshot
    await supabaseAdmin.from('enquiries').insert([
      {
        user_name: configUserName,
        user_phone: '0000000000',
        service_requested: 'SYSTEM_CONFIG_STORE',
        message: serialized,
        status: 'system_active',
      },
    ]);
  } catch (err) {
    console.error('[pollStore] Error saving poll to Supabase:', err);
  }
}

/**
 * Async API getters & mutators for routes
 */
export async function getPollStateAsync(): Promise<PollStateWithMetrics> {
  await syncFromSupabase();
  return computeMetrics(currentPoll);
}

export async function votePollAsync(option: 'yes' | 'no'): Promise<PollStateWithMetrics> {
  await syncFromSupabase();

  if (option === 'yes') {
    currentPoll.yesVotes = (currentPoll.yesVotes || 0) + 1;
  } else if (option === 'no') {
    currentPoll.noVotes = (currentPoll.noVotes || 0) + 1;
  }

  currentPoll.lastUpdated = new Date().toISOString();
  await syncToSupabase(currentPoll);
  return computeMetrics(currentPoll);
}

export async function resetPollAsync(): Promise<PollStateWithMetrics> {
  currentPoll.yesVotes = 0;
  currentPoll.noVotes = 0;
  currentPoll.lastReset = new Date().toISOString();
  currentPoll.lastUpdated = new Date().toISOString();

  await syncToSupabase(currentPoll);
  return computeMetrics(currentPoll);
}

export async function updatePollAsync(patch: Partial<PollRecord>): Promise<PollStateWithMetrics> {
  await syncFromSupabase();

  currentPoll = {
    ...currentPoll,
    ...patch,
    lastUpdated: new Date().toISOString(),
  };

  await syncToSupabase(currentPoll);
  return computeMetrics(currentPoll);
}

/**
 * Synchronous backward compatibility helpers
 */
export function getPollState(): PollStateWithMetrics {
  return computeMetrics(currentPoll);
}

export function votePoll(option: 'yes' | 'no'): PollStateWithMetrics {
  if (option === 'yes') {
    currentPoll.yesVotes = (currentPoll.yesVotes || 0) + 1;
  } else if (option === 'no') {
    currentPoll.noVotes = (currentPoll.noVotes || 0) + 1;
  }
  currentPoll.lastUpdated = new Date().toISOString();
  syncToSupabase(currentPoll).catch(() => {});
  return computeMetrics(currentPoll);
}

export function resetPoll(): PollStateWithMetrics {
  currentPoll.yesVotes = 0;
  currentPoll.noVotes = 0;
  currentPoll.lastReset = new Date().toISOString();
  currentPoll.lastUpdated = new Date().toISOString();
  syncToSupabase(currentPoll).catch(() => {});
  return computeMetrics(currentPoll);
}

export function updatePoll(patch: Partial<PollRecord>): PollStateWithMetrics {
  currentPoll = {
    ...currentPoll,
    ...patch,
    lastUpdated: new Date().toISOString(),
  };
  syncToSupabase(currentPoll).catch(() => {});
  return computeMetrics(currentPoll);
}
