import { NextResponse } from 'next/server';

export const revalidate = 60;

let pollState = {
  id: 'poll-daily-1',
  question: 'Will Coimbatore Metro Rail Phase-1 significantly ease Avinashi Road traffic congestion?',
  category: 'INFRASTRUCTURE & CIVIC',
  yesVotes: 0,
  noVotes: 0,
  active: true,
  autoGenerated: true,
  derivedFrom: 'Metro Rail DPR Ministry Approval',
  lastUpdated: new Date().toISOString(),
};

export async function GET() {
  const total = pollState.yesVotes + pollState.noVotes;
  const yesPercent = total > 0 ? Math.round((pollState.yesVotes / total) * 100) : 0;
  const noPercent = total > 0 ? 100 - yesPercent : 0;

  return NextResponse.json(
    {
      success: true,
      data: {
        ...pollState,
        totalVotes: total,
        yesPercent,
        noPercent,
      },
    },
    {
      headers: {
        'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=120',
      },
    }
  );
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    if (body.vote === 'yes') {
      pollState.yesVotes += 1;
    } else if (body.vote === 'no') {
      pollState.noVotes += 1;
    } else if (body.question) {
      pollState = {
        ...pollState,
        ...body,
        yesVotes: typeof body.yesVotes === 'number' ? body.yesVotes : 0,
        noVotes: typeof body.noVotes === 'number' ? body.noVotes : 0,
        lastUpdated: new Date().toISOString(),
      };
    }

    const total = pollState.yesVotes + pollState.noVotes;
    const yesPercent = total > 0 ? Math.round((pollState.yesVotes / total) * 100) : 0;
    const noPercent = total > 0 ? 100 - yesPercent : 0;

    return NextResponse.json({
      success: true,
      data: {
        ...pollState,
        totalVotes: total,
        yesPercent,
        noPercent,
      },
    });
  } catch (err) {
    return NextResponse.json({ success: false, error: 'Invalid payload' }, { status: 400 });
  }
}
